version: 2

defaults: &defaults
  working_directory: ~/project/vue-injector
  docker:
    - image: circleci/node:8-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-vue-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-vue-{{ .Branch }}-
            - v1-vue-
      - run: yarn install
      - save_cache:
          key: v1-vue-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - vue-injector

  lint-flow-types:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run lint
      - run: npm run flow
      - run: npm run test:types

  test-unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run test:unit
      # add codecov once it is actually ran
      # - run:
      #    name: report coverage stats for non-PRs
      #    command: |
      #      if [[ -z $CI_PULL_REQUEST ]]; then
      #        ./node_modules/.bin/codecov
      #      fi

  test-e2e:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run test:e2e
      
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/project/vue-injector/.npmrc
      - run:
          name: Publish package
          command: npm publish  > /dev/null 2>&1

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - test-unit:
          requires:
            - install
      - lint-flow-types:
          requires:
            - install
      - test-e2e:
          requires:
            - install
      - deploy:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
